### ISSUE TITLE
"Show Files" button in GUI doesn't work on Linux

### ISSUE THREAD

**Issue by tshiels** [RLBot/RLBotGUI#122]
in gui.py line 493, the line 
```python
subprocess.Popen(f'explorer "{directory}"')
```
gave me this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'explorer ~/.RLBotGUI/MyBots/tombot/src/"'

```
I changed it to this line on my machine:
``` python
subprocess.Popen(['nautilus', directory], stdout=subprocess.PIPE)
```
and that worked.

**Comment by tarehart** [comment]
Makes sense, thanks for reporting!

**Comment by VirxEC** [comment]
fixed
