### ISSUE TITLE
ConnectionAbortedError on linux

### ISSUE THREAD

**Issue by dagra** [RLBot/RLBotGUI#163]
Hi,
I'm having trouble getting it to work on linux. I constantly get the following error:

```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/username/.RLBotGUI/env/lib/python3.7/site-packages/rlbot_gui/match_runner/match_runner.py", line 222, in start_match_helper
    setup_match(sm , match_config, launcher_prefs)
  File "/home/username/.RLBotGUI/env/lib/python3.7/site-packages/rlbot_gui/match_runner/match_runner.py", line 180, in setup_match
    do_setup()
  File "/home/username/.RLBotGUI/env/lib/python3.7/site-packages/rlbot_gui/match_runner/match_runner.py", line 158, in do_setup
    setup_manager.start_match()
  File "/home/username/.RLBotGUI/env/lib/python3.7/site-packages/rlbot/setup_manager.py", line 557, in start_match
    self.game_interface.start_match()
  File "/home/username/.RLBotGUI/env/lib/python3.7/site-packages/rlbot/utils/structures/game_interface.py", line 201, in start_match
    socket_relay.connect_and_run(False, False, False)
  File "/home/username/.RLBotGUI/env/lib/python3.7/site-packages/rlbot/socket/socket_manager.py", line 116, in connect_and_run
    self.socket.connect(('127.0.0.1', 23234))
ConnectionAbortedError: [Errno 103] Software caused connection abort
2021-06-18T21:20:54Z <Greenlet at 0x7f1cfdc12830: start_match_helper([{'name': 'Psyonix Allstar', 'team': 0, 'type': 'p, {'map': 'DFHStadium', 'game_mode': 'Soccer', 'skip, RocketLeagueLauncherPreference(preferred_launcher=)> failed with ConnectionAbortedError
```
I have tried both on a desktop and a laptop, with similar specifications, i.e.: Ubuntu 20.04.2, kernel 5.4.0-74-generic and 5.8.0-55-generic, nvidia 460.80.

Steam and rocket league work great.

I have tried the following:

- Reinstalling both steam and rocket league
- Reinstalling RLBotGUI
- With steam play compatibility on & off (mainly off, since as I read in discord the linux native version must be running)
- I have also tried on a VM with Windows 10, but I couldn't make it play there either because it couldn't find the game. But I prefer to make it play on linux, since in the VM the graphics card cannot be utilized and it is laggy.

Pleasy any help would be appreciated.

**Comment by dagra** [comment]
So, as advised in discord, I pinned to version 1.54 and it seems to work.

**Comment by VirxEC** [comment]
you can now update to the latest verison of RLBot and it should work
